language: php

sudo: required
dist: trusty

addons:
  chrome: stable

cache:
  directories:
  - $HOME/.composer/cache

php:
  - '7.1'
  - nightly

install:
  - cp .env.testing .env
  - php artisan key:generate
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk
  - vendor/bin/phpunit